[workspace]
resolver = "2"

members = ["cargo-evm", "core", "macros"]

[workspace.dependencies]
patine-core = { version = "0.1", path = "./core" }
patine-macros = { version = "0.1", path = "./macros" }

[profile.release]
panic = "abort"
