[package]
name = "patine-std"
version = "0.1.0"
edition = "2021"

[[example]]
name = "store"
crate-type = ["lib"]

[[example]]
name = "array"
crate-type = ["lib"]

[dependencies]
patine-core.workspace = true
